import Head from "next/head";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>CODELAB | UNIMI</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/logo_wm.png" />
      </Head>

      <div>HELO</div>
    </>
  );
}
